### ISSUE TITLE
Dataset path structure

### ISSUE THREAD

**Issue by sovit-123** [ssaru/YOLOv1#7]
Hello, your repo has been very helpful. Can you please tell how the dataset structure should inside the data-path?

**Comment by shaotiancai** [comment]
The train or test datasets path can be available like "--data_path /VOCdevkit/VOC2007"  after extracting from the VOCtrainval_06-Nov-2007.tar or VOCtrainval_06-Nov-2007.tar.

**Comment by kiter-zero** [comment]
> Hello, your repo has been very helpful. Can you please tell how the dataset structure should inside the data-path?

The train or test datasets path can be available like "--data_path /VOCdevkit/VOC2007"  after extracting from the VOCtrainval_06-Nov-2007.tar or VOCtrainval_06-Nov-2007.tar.

**Comment by sovit-123** [comment]
Thank you.
